# Single Drug Gene Knockout Configuration
# Per-drug analysis with gene-level knockouts

output_dir: "23-12-2025_pige_graph_final/"
model_path: "data/output_data/10-17-2025_scm_per_drug_sparse_ALL_DRUGS/"

gmt_file: "data/input_data/all_pathway_genesets.gmt"
pathway_interaction_graph_file: "data/intermediate_data/all_pathway_interaction_graph.pkl"
smiles_file: "data/input_data/drugs_to_process.csv"
npvae_embeddings_file: "data/input_data/npvae_drug_embeddings.pkl"
rna_expression_file: "data/input_data/OmicsExpressionProteinCodingGenesTPMLogp1BatchCorrected.csv"
rna_map_cache_file: "data/input_data/OmicsExpressionProteinCodingGenesTPMLogp1BatchCorrected.csv.min_map.pkl"

genomic_lookups_dir: "data/intermediate_data/genomic_lookups/"
ctrpv2_drug_response_dir: "data/intermediate_data/CTRPv2_drug_response_data/"
gdsc0_drug_response_dir: "data/intermediate_data/GDSC0_drug_response_data/"
# global_genomic_lookup_file: "baseline_cell_lines/intermediate_data/genomic_lookups/ctrp_AllCellLines.pkl"

datasets_to_process:
  - "gdsc0_true_test"

drugs_to_process: []

knockout_target: "gene"
model_file_path: "data/input_data/Model.csv"
sample_n_cell_lines: null
use_top_bottom_n_cell_lines: 20

relevant_entities_file: "src/model_interpretability/relevant_entities/relevant_genes.json"
